version: '3.7'

services:
  db:
    image: postgres:14-bullseye
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    expose:
      - "5432"
    networks:
      - betting_network

  app:
    build: .
    container_name: link_provider
    volumes:
      - ./src:/app
    depends_on:
      - db
    env_file:
      - .env
    entrypoint: ["/start.sh"]
    ports:
      - "8001:8001"
    networks:
      - betting_network

volumes:
  pgdata:

networks:
  betting_network:
    external: true