version: '3.7'

services:
  postgres_bet_maker:
    image: postgres:14-bullseye
    container_name: postgres_bet_maker
    restart: always
    volumes:
      - postgres_bet_maker_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - betting_network
  redis:
    image: redis:latest
    container_name: betting_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - betting_network
  app:
    build: .
    container_name: bet_maker
    volumes:
      - ./src:/app
    depends_on:
      - postgres_bet_maker
      - redis
    env_file:
      - .env
    entrypoint: ["/start.sh"]
    ports:
      - "8000:8000"
    networks:
      - betting_network

volumes:
  postgres_bet_maker_data:
  redis_data:

networks:
  betting_network:
    external: true